language: go
go: "1.10"
sudo: false
go_import_path: github.com/samurang87/availabot

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get github.com/mattn/goveralls

install: dep ensure -vendor-only

script:
  - go test -timeout 5s -race $(go list ./... | grep -v /vendor/)
  - ./coverage.sh --coveralls

notifications:
  email: false
